spin_manifest_version = 2

[application]
name = "moscow-time"
version = "0.1.0"

[[trigger.http]]
route = "/time"
component = "moscow-time"

[component.moscow-time]
source = "main.wasm"
allowed_outbound_hosts = []
[component.moscow-time.build]
command = "GOOS=wasip1 GOARCH=wasm go build -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
