FROM golang:1.22 AS builder

WORKDIR /src

COPY go.mod ./
COPY main.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /app main.go

FROM scratch

COPY --from=builder /app /app

ENTRYPOINT ["/app"]
