name: Lab3 CI

on:
  push:
    branches: [ "main", "feature/lab3" ]

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print a greeting
        run: echo "Hello, GitHub Actions!"

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la